# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.sblogo = QtWidgets.QLabel(self.centralWidget)
        self.sblogo.setGeometry(QtCore.QRect(20, 10, 181, 181))
        self.sblogo.setText("")
        self.sblogo.setPixmap(QtGui.QPixmap(":/pictures/sblogo.png"))
        self.sblogo.setObjectName("sblogo")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(230, 10, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.Login_info = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.Login_info.setContentsMargins(1, 1, 1, 1)
        self.Login_info.setSpacing(3)
        self.Login_info.setObjectName("Login_info")
        self.label_loggedtxt = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_loggedtxt.setFont(font)
        self.label_loggedtxt.setObjectName("label_loggedtxt")
        self.Login_info.addWidget(self.label_loggedtxt)
        self.user_name = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.user_name.setMaxLength(40)
        self.user_name.setReadOnly(True)
        self.user_name.setObjectName("user_name")
        self.Login_info.addWidget(self.user_name)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 210, 451, 191))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.selector_layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.selector_layout.setContentsMargins(11, 11, 11, 11)
        self.selector_layout.setSpacing(6)
        self.selector_layout.setObjectName("selector_layout")
        self.button_A = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.button_A.setObjectName("button_A")
        self.selector_layout.addWidget(self.button_A, 0, 0, 1, 1)
        self.release_coffee_b = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.release_coffee_b.sizePolicy().hasHeightForWidth())
        self.release_coffee_b.setSizePolicy(sizePolicy)
        self.release_coffee_b.setObjectName("release_coffee_b")
        self.selector_layout.addWidget(self.release_coffee_b, 2, 0, 1, 1)
        self.button_B = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.button_B.setObjectName("button_B")
        self.selector_layout.addWidget(self.button_B, 1, 0, 1, 1)
        self.lcdNumber = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber.setLineWidth(2)
        self.lcdNumber.setMidLineWidth(1)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber.setProperty("value", 0.0)
        self.lcdNumber.setObjectName("lcdNumber")
        self.selector_layout.addWidget(self.lcdNumber, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.selector_layout.addWidget(self.label, 0, 1, 1, 1)
        self.horizontalSlider = QtWidgets.QSlider(self.gridLayoutWidget)
        self.horizontalSlider.setMinimum(15)
        self.horizontalSlider.setMaximum(60)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.selector_layout.addWidget(self.horizontalSlider, 1, 1, 1, 2)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(590, 280, 191, 121))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.userbuttons = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.userbuttons.setContentsMargins(11, 11, 11, 11)
        self.userbuttons.setSpacing(6)
        self.userbuttons.setObjectName("userbuttons")
        self.regandbalance_b = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.regandbalance_b.setObjectName("regandbalance_b")
        self.userbuttons.addWidget(self.regandbalance_b, 1, 0, 1, 1)
        self.loginout_b = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.loginout_b.setObjectName("loginout_b")
        self.userbuttons.addWidget(self.loginout_b, 0, 0, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(550, 10, 231, 251))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.Coffee_layout = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.Coffee_layout.setContentsMargins(1, 1, 1, 1)
        self.Coffee_layout.setSpacing(6)
        self.Coffee_layout.setObjectName("Coffee_layout")
        self.Coffee_A = QtWidgets.QGraphicsView(self.gridLayoutWidget_3)
        self.Coffee_A.setObjectName("Coffee_A")
        self.Coffee_layout.addWidget(self.Coffee_A, 1, 0, 1, 1)
        self.Coffee_Blabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Coffee_Blabel.setFont(font)
        self.Coffee_Blabel.setAlignment(QtCore.Qt.AlignCenter)
        self.Coffee_Blabel.setObjectName("Coffee_Blabel")
        self.Coffee_layout.addWidget(self.Coffee_Blabel, 2, 0, 1, 1)
        self.Coffee_Alabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Coffee_Alabel.setFont(font)
        self.Coffee_Alabel.setAlignment(QtCore.Qt.AlignCenter)
        self.Coffee_Alabel.setObjectName("Coffee_Alabel")
        self.Coffee_layout.addWidget(self.Coffee_Alabel, 0, 0, 1, 1)
        self.Coffee_B = QtWidgets.QGraphicsView(self.gridLayoutWidget_3)
        self.Coffee_B.setObjectName("Coffee_B")
        self.Coffee_layout.addWidget(self.Coffee_B, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.horizontalSlider.sliderMoved['int'].connect(self.lcdNumber.display)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_loggedtxt.setText(_translate("MainWindow", "Logged in as:"))
        self.button_A.setText(_translate("MainWindow", "I want premium coffee"))
        self.release_coffee_b.setText(_translate("MainWindow", "Release coffee"))
        self.button_B.setText(_translate("MainWindow", "I want economic coffee"))
        self.label.setText(_translate("MainWindow", "How many grams of coffe: "))
        self.regandbalance_b.setText(_translate("MainWindow", "Register/account"))
        self.loginout_b.setText(_translate("MainWindow", "Manual Login/Logout"))
        self.Coffee_Blabel.setText(_translate("MainWindow", "Economic coffee"))
        self.Coffee_Alabel.setText(_translate("MainWindow", "Premium coffee"))

import resource_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

