# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register_user.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RegisterUser(object):
    def setupUi(self, RegisterUser):
        RegisterUser.setObjectName("RegisterUser")
        RegisterUser.setEnabled(True)
        RegisterUser.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(RegisterUser.sizePolicy().hasHeightForWidth())
        RegisterUser.setSizePolicy(sizePolicy)
        RegisterUser.setMaximumSize(QtCore.QSize(800, 480))
        RegisterUser.setModal(False)
        self.gridLayout = QtWidgets.QGridLayout(RegisterUser)
        self.gridLayout.setObjectName("gridLayout")
        self.userinputbox = QtWidgets.QVBoxLayout()
        self.userinputbox.setObjectName("userinputbox")
        self.line_13 = QtWidgets.QFrame(RegisterUser)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.userinputbox.addWidget(self.line_13)
        self.headerlabel = QtWidgets.QLabel(RegisterUser)
        font = QtGui.QFont()
        font.setFamily("Tlwg Mono")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.headerlabel.setFont(font)
        self.headerlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.headerlabel.setObjectName("headerlabel")
        self.userinputbox.addWidget(self.headerlabel)
        self.line = QtWidgets.QFrame(RegisterUser)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.userinputbox.addWidget(self.line)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Infolabel = QtWidgets.QLabel(RegisterUser)
        font = QtGui.QFont()
        font.setFamily("Tlwg Mono")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.Infolabel.setFont(font)
        self.Infolabel.setText("")
        self.Infolabel.setObjectName("Infolabel")
        self.gridLayout_2.addWidget(self.Infolabel, 0, 1, 3, 1)
        self.entrylabel = QtWidgets.QLabel(RegisterUser)
        font = QtGui.QFont()
        font.setFamily("Tlwg Mono")
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.entrylabel.setFont(font)
        self.entrylabel.setObjectName("entrylabel")
        self.gridLayout_2.addWidget(self.entrylabel, 0, 0, 1, 1)
        self.entryinput = QtWidgets.QLineEdit(RegisterUser)
        self.entryinput.setObjectName("entryinput")
        self.gridLayout_2.addWidget(self.entryinput, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 3, 0, 1, 1)
        self.line_10 = QtWidgets.QFrame(RegisterUser)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout_2.addWidget(self.line_10, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 3, 1, 1, 1)
        self.userinputbox.addLayout(self.gridLayout_2)
        self.gridLayout.addLayout(self.userinputbox, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 1, 0, 1, 1)
        self.qwerty = QtWidgets.QGridLayout()
        self.qwerty.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.qwerty.setContentsMargins(1, 1, 1, 1)
        self.qwerty.setHorizontalSpacing(6)
        self.qwerty.setObjectName("qwerty")
        self.pushButton_del = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_del.setObjectName("pushButton_del")
        self.qwerty.addWidget(self.pushButton_del, 5, 9, 1, 1)
        self.pushButton_x = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_x.setObjectName("pushButton_x")
        self.qwerty.addWidget(self.pushButton_x, 4, 1, 1, 1)
        self.pushButton_ae = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_ae.setObjectName("pushButton_ae")
        self.qwerty.addWidget(self.pushButton_ae, 5, 0, 1, 1)
        self.pushButton_oe = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_oe.setObjectName("pushButton_oe")
        self.qwerty.addWidget(self.pushButton_oe, 5, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.qwerty.addItem(spacerItem3, 6, 2, 1, 1)
        self.pushButton_k = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_k.setObjectName("pushButton_k")
        self.qwerty.addWidget(self.pushButton_k, 3, 7, 1, 1)
        self.pushButton_h = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_h.setObjectName("pushButton_h")
        self.qwerty.addWidget(self.pushButton_h, 3, 5, 1, 1)
        self.pushButton_w = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_w.setObjectName("pushButton_w")
        self.qwerty.addWidget(self.pushButton_w, 1, 1, 1, 1)
        self.pushButton_m = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_m.setObjectName("pushButton_m")
        self.qwerty.addWidget(self.pushButton_m, 4, 6, 1, 1)
        self.pushButton_six = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_six.setObjectName("pushButton_six")
        self.qwerty.addWidget(self.pushButton_six, 0, 5, 1, 1)
        self.pushButton_d = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_d.setObjectName("pushButton_d")
        self.qwerty.addWidget(self.pushButton_d, 3, 2, 1, 1)
        self.pushButton_seven = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_seven.setObjectName("pushButton_seven")
        self.qwerty.addWidget(self.pushButton_seven, 0, 6, 1, 1)
        self.pushButton_nine = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_nine.setObjectName("pushButton_nine")
        self.qwerty.addWidget(self.pushButton_nine, 0, 8, 1, 1)
        self.pushButton_eight = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_eight.setObjectName("pushButton_eight")
        self.qwerty.addWidget(self.pushButton_eight, 0, 7, 1, 1)
        self.pushButton_i = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_i.setObjectName("pushButton_i")
        self.qwerty.addWidget(self.pushButton_i, 1, 7, 1, 1)
        self.pushButton_r = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_r.setObjectName("pushButton_r")
        self.qwerty.addWidget(self.pushButton_r, 1, 3, 1, 1)
        self.pushButton_t = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_t.setObjectName("pushButton_t")
        self.qwerty.addWidget(self.pushButton_t, 1, 4, 1, 1)
        self.pushButton_o = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_o.setObjectName("pushButton_o")
        self.qwerty.addWidget(self.pushButton_o, 1, 8, 1, 1)
        self.pushButton_f = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_f.setObjectName("pushButton_f")
        self.qwerty.addWidget(self.pushButton_f, 3, 3, 1, 1)
        self.pushButton_s = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_s.setObjectName("pushButton_s")
        self.qwerty.addWidget(self.pushButton_s, 3, 1, 1, 1)
        self.pushButton_g = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_g.setObjectName("pushButton_g")
        self.qwerty.addWidget(self.pushButton_g, 3, 4, 1, 1)
        self.pushButton_j = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_j.setObjectName("pushButton_j")
        self.qwerty.addWidget(self.pushButton_j, 3, 6, 1, 1)
        self.pushButton_zero = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_zero.setObjectName("pushButton_zero")
        self.qwerty.addWidget(self.pushButton_zero, 0, 9, 1, 1)
        self.pushButton_y = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_y.setObjectName("pushButton_y")
        self.qwerty.addWidget(self.pushButton_y, 1, 5, 1, 1)
        self.pushButton_u = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_u.setObjectName("pushButton_u")
        self.qwerty.addWidget(self.pushButton_u, 1, 6, 1, 1)
        self.pushButton_c = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_c.setObjectName("pushButton_c")
        self.qwerty.addWidget(self.pushButton_c, 4, 2, 1, 1)
        self.pushButton_p = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_p.setObjectName("pushButton_p")
        self.qwerty.addWidget(self.pushButton_p, 1, 9, 1, 1)
        self.pushButton_q = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_q.setObjectName("pushButton_q")
        self.qwerty.addWidget(self.pushButton_q, 1, 0, 1, 1)
        self.pushButton_one = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_one.setObjectName("pushButton_one")
        self.qwerty.addWidget(self.pushButton_one, 0, 0, 1, 1)
        self.pushButton_five = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_five.setObjectName("pushButton_five")
        self.qwerty.addWidget(self.pushButton_five, 0, 4, 1, 1)
        self.pushButton_n = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_n.setObjectName("pushButton_n")
        self.qwerty.addWidget(self.pushButton_n, 4, 5, 1, 1)
        self.pushButton_v = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_v.setObjectName("pushButton_v")
        self.qwerty.addWidget(self.pushButton_v, 4, 3, 1, 1)
        self.pushButton_e = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_e.setObjectName("pushButton_e")
        self.qwerty.addWidget(self.pushButton_e, 1, 2, 1, 1)
        self.pushButton_three = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_three.setObjectName("pushButton_three")
        self.qwerty.addWidget(self.pushButton_three, 0, 2, 1, 1)
        self.pushButton_dot = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_dot.setObjectName("pushButton_dot")
        self.qwerty.addWidget(self.pushButton_dot, 4, 7, 1, 1)
        self.pushButton_a = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_a.setObjectName("pushButton_a")
        self.qwerty.addWidget(self.pushButton_a, 3, 0, 1, 1)
        self.pushButton_four = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_four.setObjectName("pushButton_four")
        self.qwerty.addWidget(self.pushButton_four, 0, 3, 1, 1)
        self.pushButton_l = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_l.setObjectName("pushButton_l")
        self.qwerty.addWidget(self.pushButton_l, 3, 8, 1, 1)
        self.pushButton_b = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_b.setObjectName("pushButton_b")
        self.qwerty.addWidget(self.pushButton_b, 4, 4, 1, 1)
        self.pushButton_z = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_z.setObjectName("pushButton_z")
        self.qwerty.addWidget(self.pushButton_z, 4, 0, 1, 1)
        self.pushButton_two = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_two.setObjectName("pushButton_two")
        self.qwerty.addWidget(self.pushButton_two, 0, 1, 1, 1)
        self.pushButton_dash = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_dash.setObjectName("pushButton_dash")
        self.qwerty.addWidget(self.pushButton_dash, 4, 8, 1, 1)
        self.pushButton_Ok = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_Ok.setObjectName("pushButton_Ok")
        self.qwerty.addWidget(self.pushButton_Ok, 7, 4, 1, 2)
        self.pushButton_cancel = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.qwerty.addWidget(self.pushButton_cancel, 7, 8, 1, 2)
        self.pushButton_previous = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_previous.setObjectName("pushButton_previous")
        self.qwerty.addWidget(self.pushButton_previous, 7, 0, 1, 2)
        self.pushButton_aa = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_aa.setObjectName("pushButton_aa")
        self.qwerty.addWidget(self.pushButton_aa, 5, 2, 1, 1)
        self.pushButton_alfa = QtWidgets.QPushButton(RegisterUser)
        self.pushButton_alfa.setObjectName("pushButton_alfa")
        self.qwerty.addWidget(self.pushButton_alfa, 3, 9, 1, 1)
        self.gridLayout.addLayout(self.qwerty, 2, 0, 1, 1)

        self.retranslateUi(RegisterUser)
        QtCore.QMetaObject.connectSlotsByName(RegisterUser)

    def retranslateUi(self, RegisterUser):
        _translate = QtCore.QCoreApplication.translate
        RegisterUser.setWindowTitle(_translate("RegisterUser", "Dialog"))
        self.headerlabel.setText(_translate("RegisterUser", "Welcome to Spinbean Machine."))
        self.entrylabel.setText(_translate("RegisterUser", "Firstname:"))
        self.pushButton_del.setText(_translate("RegisterUser", "DEL"))
        self.pushButton_x.setText(_translate("RegisterUser", "X"))
        self.pushButton_ae.setText(_translate("RegisterUser", "Æ"))
        self.pushButton_oe.setText(_translate("RegisterUser", "Ø"))
        self.pushButton_k.setText(_translate("RegisterUser", "K"))
        self.pushButton_h.setText(_translate("RegisterUser", "H"))
        self.pushButton_w.setText(_translate("RegisterUser", "W"))
        self.pushButton_m.setText(_translate("RegisterUser", "M"))
        self.pushButton_six.setText(_translate("RegisterUser", "6"))
        self.pushButton_d.setText(_translate("RegisterUser", "D"))
        self.pushButton_seven.setText(_translate("RegisterUser", "7"))
        self.pushButton_nine.setText(_translate("RegisterUser", "9"))
        self.pushButton_eight.setText(_translate("RegisterUser", "8"))
        self.pushButton_i.setText(_translate("RegisterUser", "I"))
        self.pushButton_r.setText(_translate("RegisterUser", "R"))
        self.pushButton_t.setText(_translate("RegisterUser", "T"))
        self.pushButton_o.setText(_translate("RegisterUser", "O"))
        self.pushButton_f.setText(_translate("RegisterUser", "F"))
        self.pushButton_s.setText(_translate("RegisterUser", "S"))
        self.pushButton_g.setText(_translate("RegisterUser", "G"))
        self.pushButton_j.setText(_translate("RegisterUser", "J"))
        self.pushButton_zero.setText(_translate("RegisterUser", "0"))
        self.pushButton_y.setText(_translate("RegisterUser", "Y"))
        self.pushButton_u.setText(_translate("RegisterUser", "U"))
        self.pushButton_c.setText(_translate("RegisterUser", "C"))
        self.pushButton_p.setText(_translate("RegisterUser", "P"))
        self.pushButton_q.setText(_translate("RegisterUser", "Q"))
        self.pushButton_one.setText(_translate("RegisterUser", "1"))
        self.pushButton_five.setText(_translate("RegisterUser", "5"))
        self.pushButton_n.setText(_translate("RegisterUser", "N"))
        self.pushButton_v.setText(_translate("RegisterUser", "V"))
        self.pushButton_e.setText(_translate("RegisterUser", "E"))
        self.pushButton_three.setText(_translate("RegisterUser", "3"))
        self.pushButton_dot.setText(_translate("RegisterUser", "."))
        self.pushButton_a.setText(_translate("RegisterUser", "A"))
        self.pushButton_four.setText(_translate("RegisterUser", "4"))
        self.pushButton_l.setText(_translate("RegisterUser", "L"))
        self.pushButton_b.setText(_translate("RegisterUser", "B"))
        self.pushButton_z.setText(_translate("RegisterUser", "Z"))
        self.pushButton_two.setText(_translate("RegisterUser", "2"))
        self.pushButton_dash.setText(_translate("RegisterUser", "-"))
        self.pushButton_Ok.setText(_translate("RegisterUser", "OK"))
        self.pushButton_cancel.setText(_translate("RegisterUser", "Cancel"))
        self.pushButton_previous.setText(_translate("RegisterUser", "Previous"))
        self.pushButton_aa.setText(_translate("RegisterUser", "Å"))
        self.pushButton_alfa.setText(_translate("RegisterUser", "@"))

