import sys
'''Qt bindings for core Qt functionalities (non-GUI)'''
from PyQt5 import QtCore
from PyQt5 import QtGui
from PyQt5.QtWidgets import QMainWindow,QApplication, QFileDialog,QVBoxLayout
'''Subscripts'''
from mainwindow import Ui_MainWindow 		#import the MainWindow widget from the converted files from .ui to .py



'''Setup of the GUI with associated functions for buttons'''
class MainWindow(QMainWindow, Ui_MainWindow):
    def __init__(self, parent = None):
        super(MainWindow, self).__init__(parent) 	#initialization of the superclass
        self.setupUi(self) 							#setup the GUI --> function generated by pyuic4/pyuic5 depending on QT version
		
        
        


app = QApplication(sys.argv) # create the GUI application
dmw = MainWindow() # instantiate the main window
dmw.show() # show it
sys.exit(app.exec_())
