import sys
'''Qt bindings for core Qt functionalities (non-GUI)'''
from PyQt5 import QtCore
import PyQt5
import ButtonPopup
from PyQt5.QtWidgets import QMainWindow,QApplication,QDialog, QFileDialog,QVBoxLayout
'''Subscripts'''

from mainwindow import Ui_MainWindow 		#import the MainWindow widget from the converted files from .ui to .py
from pincode import Ui_pincode
from userlogin_manual import Ui_userlogin_manual



'''Setup of the GUI with associated functions for buttons'''
class MainWindow(QMainWindow, Ui_MainWindow):
    def __init__(self, parent = None):
        super(MainWindow, self).__init__(parent) 	#initialization of the superclass
        self.setupUi(self) 	#setup the GUI --> function generated by pyuic4/pyuic5 depending on QT version
        self.loginout_b.clicked.connect(self.login)

    def login(self):
        dmw.hide()
        dmf.show()


class UserLoginM(QDialog, Ui_userlogin_manual):
    def __init__(self, parent = None):
        super(UserLoginM, self).__init__(parent)
        self.setupUi(self)
        self.user_email.clear()
        self.pushButton_Ok.clicked.connect(self.submit)
        self.pushButton_cancel.clicked.connect(self.cancel)

    def submit(self):
        dmf.hide()
        dmp.show()

    def cancel(self):
        dmf.hide()
        dmw.show()

class PinCode(QDialog,Ui_pincode):
    def __init__(self, parent = None):
        super(PinCode, self).__init__(parent)
        self.setupUi(self)
        self.pushbutton_ok.clicked.connect(self.submit)
        self.pushButton_cancel.clicked.connect(self.cancel)

    def submit(self):
        dmp.hide()
        dmw.show()

    def cancel(self):
        dmp.hide()
        dmw.show()



app = QApplication(sys.argv) # create the GUI application
dmw = MainWindow() # instantiate the main window
dmf = UserLoginM()
dmp = PinCode()
dmw.show() # show it
sys.exit(app.exec_())
