# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userlogin_manual.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_userlogin_manual(object):
    def setupUi(self, userlogin_manual):
        userlogin_manual.setObjectName("userlogin_manual")
        userlogin_manual.setEnabled(True)
        userlogin_manual.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(userlogin_manual.sizePolicy().hasHeightForWidth())
        userlogin_manual.setSizePolicy(sizePolicy)
        userlogin_manual.setMaximumSize(QtCore.QSize(800, 480))
#        userlogin_manual.setModal(False)
        self.gridLayout = QtWidgets.QGridLayout(userlogin_manual)
        self.gridLayout.setObjectName("gridLayout")
        self.userinputbox = QtWidgets.QVBoxLayout()
        self.userinputbox.setObjectName("userinputbox")
        self.label = QtWidgets.QLabel(userlogin_manual)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.userinputbox.addWidget(self.label)
        self.user_email = QtWidgets.QLineEdit(userlogin_manual)
        self.user_email.setMaxLength(50)
        self.user_email.setObjectName("user_email")
        self.userinputbox.addWidget(self.user_email)
        self.gridLayout.addLayout(self.userinputbox, 0, 0, 1, 1)
        self.qwerty = QtWidgets.QGridLayout()
        self.qwerty.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.qwerty.setContentsMargins(1, 1, 1, 1)
        self.qwerty.setHorizontalSpacing(6)
        self.qwerty.setObjectName("qwerty")
        self.pushButton_k = QtWidgets.QPushButton(userlogin_manual)
        self.pushButton_k.setObjectName("pushButton_k")
        self.qwerty.addWidget(self.pushButton_k, 2, 7, 1, 1)
        self.pushButton_h = QtWidgets.QPushButton(userlogin_manual)
        self.pushButton_h.setObjectName("pushButton_h")
        self.qwerty.addWidget(self.pushButton_h, 2, 5, 1, 1)
        self.pushButton_m = QtWidgets.QPushButton(userlogin_manual)
        self.pushButton_m.setObjectName("pushButton_m")
        self.qwerty.addWidget(self.pushButton_m, 3, 6, 1, 1)
        self.pushButton_w = QtWidgets.QPushButton(userlogin_manual)
        self.pushButton_w.setObjectName("pushButton_w")
        self.qwerty.addWidget(self.pushButton_w, 1, 1, 1, 1)
        self.pushButton_six = QtWidgets.QPushButton(userlogin_manual)
        self.pushButton_six.setObjectName("pushButton_six")
        self.qwerty.addWidget(self.pushButton_six, 0, 5, 1, 1)
        self.pushButton_d = QtWidgets.QPushButton(userlogin_manual)
        self.pushButton_d.setObjectName("pushButton_d")
        self.qwerty.addWidget(self.pushButton_d, 2, 2, 1, 1)
        self.pushButton_seven = QtWidgets.QPushButton(userlogin_manual)
        self.pushButton_seven.setObjectName("pushButton_seven")
        self.qwerty.addWidget(self.pushButton_seven, 0, 6, 1, 1)
        self.pushButton_nine = QtWidgets.QPushButton(userlogin_manual)
        self.pushButton_nine.setObjectName("pushButton_nine")
        self.qwerty.addWidget(self.pushButton_nine, 0, 8, 1, 1)
        self.pushButton_eight = QtWidgets.QPushButton(userlogin_manual)
        self.pushButton_eight.setObjectName("pushButton_eight")
        self.qwerty.addWidget(self.pushButton_eight, 0, 7, 1, 1)
        self.pushButton_i = QtWidgets.QPushButton(userlogin_manual)
        self.pushButton_i.setObjectName("pushButton_i")
        self.qwerty.addWidget(self.pushButton_i, 1, 7, 1, 1)
        self.pushButton_r = QtWidgets.QPushButton(userlogin_manual)
        self.pushButton_r.setObjectName("pushButton_r")
        self.qwerty.addWidget(self.pushButton_r, 1, 3, 1, 1)
        self.pushButton_t = QtWidgets.QPushButton(userlogin_manual)
        self.pushButton_t.setObjectName("pushButton_t")
        self.qwerty.addWidget(self.pushButton_t, 1, 4, 1, 1)
        self.pushButton_o = QtWidgets.QPushButton(userlogin_manual)
        self.pushButton_o.setObjectName("pushButton_o")
        self.qwerty.addWidget(self.pushButton_o, 1, 8, 1, 1)
        self.pushButton_del = QtWidgets.QPushButton(userlogin_manual)
        self.pushButton_del.setObjectName("pushButton_del")
        self.qwerty.addWidget(self.pushButton_del, 3, 9, 1, 1)
        self.pushButton_f = QtWidgets.QPushButton(userlogin_manual)
        self.pushButton_f.setObjectName("pushButton_f")
        self.qwerty.addWidget(self.pushButton_f, 2, 3, 1, 1)
        self.pushButton_s = QtWidgets.QPushButton(userlogin_manual)
        self.pushButton_s.setObjectName("pushButton_s")
        self.qwerty.addWidget(self.pushButton_s, 2, 1, 1, 1)
        self.pushButton_g = QtWidgets.QPushButton(userlogin_manual)
        self.pushButton_g.setObjectName("pushButton_g")
        self.qwerty.addWidget(self.pushButton_g, 2, 4, 1, 1)
        self.pushButton_j = QtWidgets.QPushButton(userlogin_manual)
        self.pushButton_j.setObjectName("pushButton_j")
        self.qwerty.addWidget(self.pushButton_j, 2, 6, 1, 1)
        self.pushButton_zero = QtWidgets.QPushButton(userlogin_manual)
        self.pushButton_zero.setObjectName("pushButton_zero")
        self.qwerty.addWidget(self.pushButton_zero, 0, 9, 1, 1)
        self.pushButton_y = QtWidgets.QPushButton(userlogin_manual)
        self.pushButton_y.setObjectName("pushButton_y")
        self.qwerty.addWidget(self.pushButton_y, 1, 5, 1, 1)
        self.pushButton_u = QtWidgets.QPushButton(userlogin_manual)
        self.pushButton_u.setObjectName("pushButton_u")
        self.qwerty.addWidget(self.pushButton_u, 1, 6, 1, 1)
        self.pushButton_c = QtWidgets.QPushButton(userlogin_manual)
        self.pushButton_c.setObjectName("pushButton_c")
        self.qwerty.addWidget(self.pushButton_c, 3, 2, 1, 1)
        self.pushButton_x = QtWidgets.QPushButton(userlogin_manual)
        self.pushButton_x.setObjectName("pushButton_x")
        self.qwerty.addWidget(self.pushButton_x, 3, 1, 1, 1)
        self.pushButton_p = QtWidgets.QPushButton(userlogin_manual)
        self.pushButton_p.setObjectName("pushButton_p")
        self.qwerty.addWidget(self.pushButton_p, 1, 9, 1, 1)
        self.pushButton_q = QtWidgets.QPushButton(userlogin_manual)
        self.pushButton_q.setObjectName("pushButton_q")
        self.qwerty.addWidget(self.pushButton_q, 1, 0, 1, 1)
        self.pushButton_one = QtWidgets.QPushButton(userlogin_manual)
        self.pushButton_one.setObjectName("pushButton_one")
        self.qwerty.addWidget(self.pushButton_one, 0, 0, 1, 1)
        self.pushButton_five = QtWidgets.QPushButton(userlogin_manual)
        self.pushButton_five.setObjectName("pushButton_five")
        self.qwerty.addWidget(self.pushButton_five, 0, 4, 1, 1)
        self.pushButton_alfa = QtWidgets.QPushButton(userlogin_manual)
        self.pushButton_alfa.setObjectName("pushButton_alfa")
        self.qwerty.addWidget(self.pushButton_alfa, 2, 9, 1, 1)
        self.pushButton_v = QtWidgets.QPushButton(userlogin_manual)
        self.pushButton_v.setObjectName("pushButton_v")
        self.qwerty.addWidget(self.pushButton_v, 3, 3, 1, 1)
        self.pushButton_n = QtWidgets.QPushButton(userlogin_manual)
        self.pushButton_n.setObjectName("pushButton_n")
        self.qwerty.addWidget(self.pushButton_n, 3, 5, 1, 1)
        self.pushButton_three = QtWidgets.QPushButton(userlogin_manual)
        self.pushButton_three.setObjectName("pushButton_three")
        self.qwerty.addWidget(self.pushButton_three, 0, 2, 1, 1)
        self.pushButton_dot = QtWidgets.QPushButton(userlogin_manual)
        self.pushButton_dot.setObjectName("pushButton_dot")
        self.qwerty.addWidget(self.pushButton_dot, 3, 7, 1, 1)
        self.pushButton_e = QtWidgets.QPushButton(userlogin_manual)
        self.pushButton_e.setObjectName("pushButton_e")
        self.qwerty.addWidget(self.pushButton_e, 1, 2, 1, 1)
        self.pushButton_a = QtWidgets.QPushButton(userlogin_manual)
        self.pushButton_a.setObjectName("pushButton_a")
        self.qwerty.addWidget(self.pushButton_a, 2, 0, 1, 1)
        self.pushButton_four = QtWidgets.QPushButton(userlogin_manual)
        self.pushButton_four.setObjectName("pushButton_four")
        self.qwerty.addWidget(self.pushButton_four, 0, 3, 1, 1)
        self.pushButton_l = QtWidgets.QPushButton(userlogin_manual)
        self.pushButton_l.setObjectName("pushButton_l")
        self.qwerty.addWidget(self.pushButton_l, 2, 8, 1, 1)
        self.pushButton_b = QtWidgets.QPushButton(userlogin_manual)
        self.pushButton_b.setObjectName("pushButton_b")
        self.qwerty.addWidget(self.pushButton_b, 3, 4, 1, 1)
        self.pushButton_z = QtWidgets.QPushButton(userlogin_manual)
        self.pushButton_z.setObjectName("pushButton_z")
        self.qwerty.addWidget(self.pushButton_z, 3, 0, 1, 1)
        self.pushButton_two = QtWidgets.QPushButton(userlogin_manual)
        self.pushButton_two.setObjectName("pushButton_two")
        self.qwerty.addWidget(self.pushButton_two, 0, 1, 1, 1)
        self.pushButton_dash = QtWidgets.QPushButton(userlogin_manual)
        self.pushButton_dash.setObjectName("pushButton_dash")
        self.qwerty.addWidget(self.pushButton_dash, 3, 8, 1, 1)
        self.pushButton_cancel = QtWidgets.QPushButton(userlogin_manual)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.qwerty.addWidget(self.pushButton_cancel, 4, 7, 1, 1)
        self.pushButton_Ok = QtWidgets.QPushButton(userlogin_manual)
        self.pushButton_Ok.setObjectName("pushButton_Ok")
        self.qwerty.addWidget(self.pushButton_Ok, 4, 8, 1, 1)
        self.gridLayout.addLayout(self.qwerty, 1, 0, 1, 1)

        self.retranslateUi(userlogin_manual)
        QtCore.QMetaObject.connectSlotsByName(userlogin_manual)

    def retranslateUi(self, userlogin_manual):
        _translate = QtCore.QCoreApplication.translate
        userlogin_manual.setWindowTitle(_translate("userlogin_manual", "Dialog"))
        self.label.setText(_translate("userlogin_manual", "Please enter your email credentials"))
        self.pushButton_k.setText(_translate("userlogin_manual", "K"))
        self.pushButton_h.setText(_translate("userlogin_manual", "H"))
        self.pushButton_m.setText(_translate("userlogin_manual", "M"))
        self.pushButton_w.setText(_translate("userlogin_manual", "W"))
        self.pushButton_six.setText(_translate("userlogin_manual", "6"))
        self.pushButton_d.setText(_translate("userlogin_manual", "D"))
        self.pushButton_seven.setText(_translate("userlogin_manual", "7"))
        self.pushButton_nine.setText(_translate("userlogin_manual", "9"))
        self.pushButton_eight.setText(_translate("userlogin_manual", "8"))
        self.pushButton_i.setText(_translate("userlogin_manual", "I"))
        self.pushButton_r.setText(_translate("userlogin_manual", "R"))
        self.pushButton_t.setText(_translate("userlogin_manual", "T"))
        self.pushButton_o.setText(_translate("userlogin_manual", "O"))
        self.pushButton_del.setText(_translate("userlogin_manual", "DEL"))
        self.pushButton_f.setText(_translate("userlogin_manual", "F"))
        self.pushButton_s.setText(_translate("userlogin_manual", "S"))
        self.pushButton_g.setText(_translate("userlogin_manual", "G"))
        self.pushButton_j.setText(_translate("userlogin_manual", "J"))
        self.pushButton_zero.setText(_translate("userlogin_manual", "0"))
        self.pushButton_y.setText(_translate("userlogin_manual", "Y"))
        self.pushButton_u.setText(_translate("userlogin_manual", "U"))
        self.pushButton_c.setText(_translate("userlogin_manual", "C"))
        self.pushButton_x.setText(_translate("userlogin_manual", "X"))
        self.pushButton_p.setText(_translate("userlogin_manual", "P"))
        self.pushButton_q.setText(_translate("userlogin_manual", "Q"))
        self.pushButton_one.setText(_translate("userlogin_manual", "1"))
        self.pushButton_five.setText(_translate("userlogin_manual", "5"))
        self.pushButton_alfa.setText(_translate("userlogin_manual", "@"))
        self.pushButton_v.setText(_translate("userlogin_manual", "V"))
        self.pushButton_n.setText(_translate("userlogin_manual", "N"))
        self.pushButton_three.setText(_translate("userlogin_manual", "3"))
        self.pushButton_dot.setText(_translate("userlogin_manual", "."))
        self.pushButton_e.setText(_translate("userlogin_manual", "E"))
        self.pushButton_a.setText(_translate("userlogin_manual", "A"))
        self.pushButton_four.setText(_translate("userlogin_manual", "4"))
        self.pushButton_l.setText(_translate("userlogin_manual", "L"))
        self.pushButton_b.setText(_translate("userlogin_manual", "B"))
        self.pushButton_z.setText(_translate("userlogin_manual", "Z"))
        self.pushButton_two.setText(_translate("userlogin_manual", "2"))
        self.pushButton_dash.setText(_translate("userlogin_manual", "-"))
        self.pushButton_cancel.setText(_translate("userlogin_manual", "Cancel"))
        self.pushButton_Ok.setText(_translate("userlogin_manual", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    userlogin_manual = QtWidgets.QDialog()
    ui = Ui_userlogin_manual()
    ui.setupUi(userlogin_manual)
    userlogin_manual.show()
    sys.exit(app.exec_())

